### ISSUE TITLE
Application crashes when certificates are expired

### ISSUE THREAD

**Issue by sanatsathaye** [mudkipme/MoeMemosAndroid#224]
There was some issue with the certbot setup on my server (HSTS enabled) and my certificates didn't renew. But that doesn't mean the application should crash immediately when I launch it, it should handle the problem more gracefully because right now I can't even open the app.

Using 0.8.3 Play Store version.

```
FATAL EXCEPTION: main
Process: me.mudkip.moememos, PID: 9716
javax.net.ssl.SSLHandshakeException: Chain validation failed
    at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:358)
    at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1131)
    at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1086)
    at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:873)
    at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:744)
    at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:709)
    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:898)
    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
    at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
    at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
    at Y4.l.g(Unknown Source:106)
    at Y4.l.c(Unknown Source:167)
    at Y4.f.a(Unknown Source:733)
    at Y4.a.a(Unknown Source:59)
    at Z4.f.b(Unknown Source:123)
    at W4.b.a(Unknown Source:132)
    at Z4.f.b(Unknown Source:123)
    at Z4.a.a(Unknown Source:704)
    at Z4.f.b(Unknown Source:123)
    at Z4.a.a(Unknown Source:151)
    at Z4.f.b(Unknown Source:123)
    at Y4.j.f(Unknown Source:96)
    at Y4.g.run(Unknown Source:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
    Suppressed: q4.f: [v0{Cancelling}@249f0a5, Dispatchers.Main.immediate]
Caused by: java.security.cert.CertificateException: Chain validation failed
    at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:724)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:575)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:620)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:430)
    at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:358)
    at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
    at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
    at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:165)
    at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:269)
    at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1635)
    at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
    at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:572)
    at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1092)
    at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1076)
    ... 23 more
Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
    at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
    at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
    at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:720)
    ... 38 more
Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Tue Dec 24 11:24:10 GMT+05:30 2024 (compared to Mon Dec 30 14:00:39 GMT+05:30 2024)
    at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:272)
    at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
    at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
    ... 43 more
```

**Comment by jkuhlemann** [comment]
I agree, the app needs better error handling when there are any issues with the server
